sudo: required
services:
  - docker
install:
  - docker pull jderusse/gitsplit:golang
  - git config remote.origin.fetch "+refs/*:refs/*"
  - git config remote.origin.mirror true
  - git fetch --unshallow || true
script:
  - docker run --rm -t -e GH_TOKEN -v ${PWD}:/srv jderusse/gitsplit:golang

#Â Contains the GH_TOKEN encrypted.
#  See https://docs.travis-ci.com/user/encryption-keys/
#  Token generated in https://github.com/settings/tokens with permission "repo/public_repo"
env:
  global:
    secure: WmXf6bKIggWAYsTTuGyojojZmMuj+iT/0li946rmFpbQVbL6FImjPkJIFB1rcZanVsSO3SJwz/M2BBEX/2MmMARO4tB5+37ESqog5SHzsweJd3oO5eVWu1OWs3I9aAhwNqDXT2LxWWUbBp1uZvLH4sAcKP9xX+LAnjEoV4vndwKvEuGLYKJRYaMGxdt4W1jPohsvS3ZPTI6ns14EGHqk1bYnKxw3Q0nVidWAAdrb4szOYtQB+R2aLWQ3zo61lVCaKoELsKgESetwNngAVrgLX5qH6zhiq3QmeNiAaOQd548kFqufo8AafFZ0gDxEQlMXYQ4xN38IMMKN/cNnF4HralXOAtvF3qA5z/KsbPLA23WqpkjabmJQ07KIFeMiP6mWLuFpnkMV5D4F/+r218g4Wmh7XikStqE4dQYdjACCVK/4HyXu70qDVRulc+B7OICsGxrNHVPLLxD8Wf37/68BGL+Mzi3GE2DjZJIoW0ElXK7+31gaSolIB9YaA/1IyuZY5hzLwMH7RhqJV3fTrPOJeGx+TVgppPDX5tPWZYYNjhOZnvsxVHlOQ/Sp5Z/dXq4TC4UEkAeXskRGpjjyF58lw0NckBQwDtoM0naDGUGrk09NjtLeIydFMvksGat7sVfVJY5V7N34m2s5NSuRG9j6v8QS56RJS6BkWpdez5Gc340=
